language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-28

before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-28 --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 10
  - adb shell input keyevent 82

env:
  matrix:
    - TEST=:preferenceholder:connectedDebugAndroidTest
    - TEST=:preferenceholder-gson-serializer:connectedDebugAndroidTest

script:
  - ./gradlew $TEST -i

branches:
  only:
  - master
  - stable

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle